### PR TITLE
add style injection from theme css file

### PR DESCRIPTION
**Pull request by av8ta**
add standard formatting
skip node_modules

Saw this comment and ran with it!

> /* Hardcode the theme, should be overriden by Agregore theme vars*/

Is this how you wanted to do it?

### CODE REVIEW

**Comment by RangerMauve** [comment]
Oh cool! I think the comment I had was initially there to remind me about the `theme.json` functionality, but I like the idea of being able to pass in a stylesheet. 

What do you think about using a `style.css` inside the root of the input folder to read from, or passing in a string into `renderMarkdown`? I think the CSS in JSON stuff might be a bit unnecessary. 😅 (also harder to support stuff like animations and the such)

**Comment by av8ta** [comment]
> What do you think about using a style.css inside the root of the input folder to read from

Agree a css file is a better idea! But not sure what you mean by "root o input folder"?

**Comment by RangerMauve** [comment]
Err, by `root o input folder` I meant to look up the css file in the folder that's being used as the `--input` argument. 😅 Kinda like how `theme.json` works at the moment.

https://github.com/AgregoreWeb/agregore-markdown-site-generator/blob/3fbf40289fec0e68573d7d7a96ad956ba18880d6/index.js#L19

**Comment by av8ta** [comment]
Okay that makes sense :sweat: 
I've got a little contracting work to do at the moment, and I've been experimenting with making a new ssb database for kicks too. I'll be back on agregore stuff soon :pray:

**Comment by av8ta** [comment]
Hi @RangerMauve I had the need for an ssg so circled back round to this! Defaults to inlining css. `default.css` and then `theme.css` to override it if a theme.css is present. This way the behaviour is the same as before.

You can also pass a flag to link `default.css` in the head tag, with theme injected in a style tag. Since the theme is just css variables it's small, meaning the pages are all smaller than before. `default.css` is written to the output folder so it all "just works".

**Pull request closed without merging**
